"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var QuerySyntaxEnum;
(function (QuerySyntaxEnum) {
    QuerySyntaxEnum[QuerySyntaxEnum["Undefined"] = -1] = "Undefined";
    QuerySyntaxEnum[QuerySyntaxEnum["And"] = 0] = "And";
    QuerySyntaxEnum[QuerySyntaxEnum["Are"] = 1] = "Are";
    QuerySyntaxEnum[QuerySyntaxEnum["Between"] = 2] = "Between";
    QuerySyntaxEnum[QuerySyntaxEnum["EQ"] = 3] = "EQ";
    QuerySyntaxEnum[QuerySyntaxEnum["GT"] = 4] = "GT";
    QuerySyntaxEnum[QuerySyntaxEnum["Is"] = 5] = "Is";
    QuerySyntaxEnum[QuerySyntaxEnum["Like"] = 6] = "Like";
    QuerySyntaxEnum[QuerySyntaxEnum["Limit"] = 7] = "Limit";
    QuerySyntaxEnum[QuerySyntaxEnum["LT"] = 8] = "LT";
    QuerySyntaxEnum[QuerySyntaxEnum["Not"] = 9] = "Not";
    QuerySyntaxEnum[QuerySyntaxEnum["Or"] = 10] = "Or";
    QuerySyntaxEnum[QuerySyntaxEnum["OrderBy"] = 11] = "OrderBy";
    QuerySyntaxEnum[QuerySyntaxEnum["Delete"] = 12] = "Delete";
    QuerySyntaxEnum[QuerySyntaxEnum["Select"] = 13] = "Select";
    QuerySyntaxEnum[QuerySyntaxEnum["Set"] = 14] = "Set";
    QuerySyntaxEnum[QuerySyntaxEnum["Update"] = 15] = "Update";
    QuerySyntaxEnum[QuerySyntaxEnum["Where"] = 16] = "Where";
    QuerySyntaxEnum[QuerySyntaxEnum["To"] = 17] = "To";
    QuerySyntaxEnum[QuerySyntaxEnum["Insert"] = 18] = "Insert";
    QuerySyntaxEnum[QuerySyntaxEnum["From"] = 19] = "From";
    QuerySyntaxEnum[QuerySyntaxEnum["Null"] = 20] = "Null";
    QuerySyntaxEnum[QuerySyntaxEnum["Exists"] = 21] = "Exists";
    QuerySyntaxEnum[QuerySyntaxEnum["Coalesce"] = 22] = "Coalesce";
    QuerySyntaxEnum[QuerySyntaxEnum["Greatest"] = 23] = "Greatest";
    QuerySyntaxEnum[QuerySyntaxEnum["Least"] = 24] = "Least";
    QuerySyntaxEnum[QuerySyntaxEnum["On"] = 25] = "On";
    QuerySyntaxEnum[QuerySyntaxEnum["LeftJoin"] = 26] = "LeftJoin";
    QuerySyntaxEnum[QuerySyntaxEnum["RightJoin"] = 27] = "RightJoin";
    QuerySyntaxEnum[QuerySyntaxEnum["Join"] = 28] = "Join";
    QuerySyntaxEnum[QuerySyntaxEnum["FullJoin"] = 29] = "FullJoin";
    QuerySyntaxEnum[QuerySyntaxEnum["Union"] = 30] = "Union";
    QuerySyntaxEnum[QuerySyntaxEnum["WrapInParentheses"] = 31] = "WrapInParentheses";
    QuerySyntaxEnum[QuerySyntaxEnum["OpenParentheses"] = 32] = "OpenParentheses";
    QuerySyntaxEnum[QuerySyntaxEnum["CloseParentheses"] = 33] = "CloseParentheses";
    QuerySyntaxEnum[QuerySyntaxEnum["Alias"] = 34] = "Alias";
    QuerySyntaxEnum[QuerySyntaxEnum["RowId"] = 35] = "RowId";
    QuerySyntaxEnum[QuerySyntaxEnum["Min"] = 36] = "Min";
    QuerySyntaxEnum[QuerySyntaxEnum["Max"] = 37] = "Max";
    QuerySyntaxEnum[QuerySyntaxEnum["Sum"] = 38] = "Sum";
    QuerySyntaxEnum[QuerySyntaxEnum["Avg"] = 39] = "Avg";
    QuerySyntaxEnum[QuerySyntaxEnum["Sqrt"] = 40] = "Sqrt";
    QuerySyntaxEnum[QuerySyntaxEnum["Pow"] = 41] = "Pow";
    QuerySyntaxEnum[QuerySyntaxEnum["Count"] = 42] = "Count";
    QuerySyntaxEnum[QuerySyntaxEnum["GroupBy"] = 43] = "GroupBy";
})(QuerySyntaxEnum = exports.QuerySyntaxEnum || (exports.QuerySyntaxEnum = {}));
var FilterResultEnum;
(function (FilterResultEnum) {
    FilterResultEnum[FilterResultEnum["Failed"] = 0] = "Failed";
    FilterResultEnum[FilterResultEnum["Passed"] = 1] = "Passed";
    FilterResultEnum[FilterResultEnum["Skipped"] = 2] = "Skipped";
})(FilterResultEnum = exports.FilterResultEnum || (exports.FilterResultEnum = {}));
var SortingOrderEnum;
(function (SortingOrderEnum) {
    SortingOrderEnum[SortingOrderEnum["ASC"] = 1] = "ASC";
    SortingOrderEnum[SortingOrderEnum["DESC"] = -1] = "DESC";
})(SortingOrderEnum = exports.SortingOrderEnum || (exports.SortingOrderEnum = {}));
//# sourceMappingURL=enums.js.map